const DummyMeals = [
    {
        id: 1,
        meal_name: 'Vadouvan Spiced Vegetables',
        meal_description: 'Sautéed Seasonal Vegetables, Crispy Corn Cake with Coconut-Vadouvan Jus and Pickled Mustard Seeds',
        restaurant_name: 'Be Our Guest',
        park_location: 'Magic Kingdom',
        price: '$62.00',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'no',
    },
    {
        id: 2,
        meal_name: 'Chickpea Panisse',
        meal_description: 'Sautéed SeasCrispy Chickpeas Panisse, Tomato Jam, Roasted Carrots, Chermoula-spiced Garbanzos, and Chive Powder',
        restaurant_name: "Cinderella's Royal Table",
        park_location: 'Magic Kingdom',
        price: '$62.00',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'yes',
    },    {
        id: 3,
        meal_name: 'BBQ Jackfruit Burger',
        meal_description: 'Plant-based Burger on Garlic Toast topped with BBQ Jackfruit, Plant-based Mayonnaise and Lettuce served with your choice of side',
        restaurant_name: 'Regal Eagle Smokehouse',
        park_location: 'Epcot',
        price: '$12.99',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'no',
    },    
    {
        id: 4,
        meal_name: 'Grilled Vegetable Skewer with Impossible™ Kefta',
        meal_description: 'Basmati Rice, Lentils, Smoked Eggplant Salad',
        restaurant_name: 'Coral Reef',
        park_location: 'Epcot',
        price: '$24.00',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'no',
    },    {
        id: 5,
        meal_name: "Cousin Harold's Vegetable Garden",
        meal_description: 'A Seasonal Alternative with all the Fixings',
        restaurant_name: "50's Prime Time Cafe",
        park_location: 'Hollywood Studios',
        price: 'Market Price',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'no',
    },    {
        id: 6,
        meal_name: 'Hot Link Smokehouse Sandwich',
        meal_description: 'Plant-based Sausage topped with a Tangy Mustard Barbecue Sauce, Slaw, and Crispy Onions on a House-made New England-style Roll',
        restaurant_name: 'Flame Tree Barbecue',
        park_location: 'Animal Kingdom',
        price: '$12.99',
        vegan: 'yes',
        vegetarian: 'yes',
        gluten_free: 'no',
    },
]

export default DummyMeals